# SPDX-FileCopyrightText: © 2023 Technical University of Munich, Chair of Connected Mobility
# SPDX-License-Identifier: MIT
[workspace]

[package]
name = "edgeless-embedded-esp32"
version = "0.1.0"
authors = ["Raphael Hetzel <hetzel@in.tum.de>>"]
edition = "2021"
resolver = "2"
rust-version = "1.73"

[profile.dev.package.esp-wifi]
opt-level = 3

[profile.release]
opt-level = "s"
lto = "off"

[profile.dev]
debug = true
opt-level = 3
lto = "off"

[dependencies]
log = { version = "0.4", default-features = false }
embedded-hal = "1"
embedded-hal-async = "1"
embedded-hal-bus = { version = "0.2", features = ["async"] }
esp-alloc = { version = "0.7.0" }


embassy-executor = { version = "0.7.0", features = ["nightly"] }
embassy-sync = { version = "0.6" }
embassy-time = { version = "0.4", features = ["tick-hz-1_000_000"] }
embassy-net = { version = "0.6", features = [
    "tcp",
    "udp",
    "dhcpv4",
    "medium-ethernet",
    "proto-ipv4"
] }
embassy-futures = { version = "0.1" }
embassy-embedded-hal = { version = "0.3" }

static_cell = { version = "1.2.0" }
heapless = "0.8"
once_cell = { version = "1.18", default-features = false, features = [
    "critical-section",
] }

embedded-svc = { version = "0.25.1", default-features = false, features = [] }

getrandom = { version = "0.3" }
uuid = { version = "1.3", default-features = false, features = ["v4"] }

edgeless_embedded = { path = "../edgeless_embedded", features=["nightly"] }
edgeless_api_core = { path = "../edgeless_api_core" }

epd-waveshare = { git = "https://github.com/edgeless-project/epd-waveshare.git", branch = "edgeless_fork", features = [
    "graphics",
    "epd2in13_v3",
], default-features = false }
embedded-graphics = { version = "0.8" }
sensor-scd30 = { git = "https://github.com/edgeless-project/rust-sensor-scd30.git", branch = "edgeless_fork", default-features = false }
cfg-if = "1.0"


[target.xtensa-esp32-none-elf.dependencies]
esp-hal = { version = "1.0.0-beta.0", features = ["unstable"] }
esp-backtrace = { version = "0.15", features = [
    "esp32",
    "panic-handler",
    "exception-handler",
    "println",
] }
esp-println = { version = "0.13", default-features = false, features = [
    "esp32",
    "uart",
    "log",
    "critical-section",
] }
esp-wifi = { version = "0.13", default_features = false, features = [
    "esp32",
    "wifi",
    "builtin-scheduler",
] }
esp-hal-embassy = { version = "0.7.0", features = ["esp32"] }

[target.xtensa-esp32s3-none-elf.dependencies]
esp-hal = { version = "1.0.0-beta.0", features = ["unstable"] }
esp-backtrace = { version = "0.15", features = [
    "esp32s3",
    "panic-handler",
    "exception-handler",
    "println",
] }
esp-println = { version = "0.13", default-features = false, features = [
    "esp32s3",
    "uart",
    "log",
    "critical-section",
] }
esp-wifi = { version = "0.13", default_features = false, features = [
    "esp32s3",
    "wifi",
    "builtin-scheduler",
    "log",
] }
esp-hal-embassy = { version = "0.7.0", features = ["esp32s3"] }

[features]
# GDEH0213B73
epaper_2_13 = []
scd30 = []
tum_node_2_13 = ["epaper_2_13", "scd30", "esp32"]
esp32 = []
wasm = []
psram = ["esp-hal/psram", "edgeless_embedded/alloc_static"]

[build-dependencies]
embuild = "0.31.2"
