instances = [
    {
        "id": 1,
        "left": 2,
        "right": None,
        "bottom": 6,
        "top": None,
        "top_left": None,
        "top_right": None,
        "bottom_left": 7,
        "bottom_right": None,
        "position_x": 2,
        "position_y": 0,
    },
    {
        "id": 2,
        "left": 3,
        "right": 1,
        "bottom": 7,
        "top": None,
        "top_left": None,
        "top_right": None,
        "bottom_left": 8,
        "bottom_right": 6,
        "position_x": 1,
        "position_y": 0,
    },
    {
        "id": 3,
        "left": None,
        "right": 2,
        "bottom": 8,
        "top": None,
        "top_left": None,
        "top_right": None,
        "bottom_left": None,
        "bottom_right": 7,
        "position_x": 0,
        "position_y": 0,
    },
    {
        "id": 6,
        "left": 7,
        "right": None,
        "bottom": 11,
        "top": 1,
        "top_left": 2,
        "top_right": None,
        "bottom_left": 12,
        "bottom_right": None,
        "position_x": 2,
        "position_y": 1,
    },
    {
        "id": 7,
        "left": 8,
        "right": 6,
        "bottom": 12,
        "top": 2,
        "top_left": 3,
        "top_right": 1,
        "bottom_left": 13,
        "bottom_right": 11,
        "position_x": 1,
        "position_y": 1,
    },
    {
        "id": 8,
        "left": None,
        "right": 2,
        "bottom": 13,
        "top": 3,
        "top_left": None,
        "top_right": None,
        "bottom_left": None,
        "bottom_right": 12,
        "position_x": 0,
        "position_y": 1,
    },
    {
        "id": 11,
        "left": 12,
        "right": None,
        "bottom": None,
        "top": 6,
        "top_left": 7,
        "top_right": None,
        "bottom_left": None,
        "bottom_right": None,
        "position_x": 2,
        "position_y": 2,
    },
    {
        "id": 12,
        "left": 13,
        "right": 11,
        "bottom": None,
        "top": 7,
        "top_left": 8,
        "top_right": 6,
        "bottom_left": None,
        "bottom_right": None,
        "position_x": 1,
        "position_y": 2,
    },
    {
        "id": 13,
        "left": None,
        "right": 12,
        "bottom": None,
        "top": 8,
        "top_left": None,
        "top_right": 7,
        "bottom_left": None,
        "bottom_right": None,
        "position_x": 0,
        "position_y": 2,
    },
]
