instances = [
    {
        "id": 1,
        "left": 2,
        "right": None,
        "bottom": 6,
        "top": None,
        "top_left": None,
        "top_right": None,
        "bottom_left": 7,
        "bottom_right": None,
        "position_x": 1,
        "position_y": 0,
    },
    {
        "id": 2,
        "left": None,
        "right": 1,
        "bottom": 7,
        "top": None,
        "top_left": None,
        "top_right": None,
        "bottom_left": None,
        "bottom_right": 6,
        "position_x": 0,
        "position_y": 0,
    },
    {
        "id": 6,
        "left": 7,
        "right": None,
        "bottom": None,
        "top": 1,
        "top_left": 2,
        "top_right": None,
        "bottom_left": None,
        "bottom_right": None,
        "position_x": 1,
        "position_y": 1,
    },
    {
        "id": 7,
        "left": None,
        "right": 6,
        "bottom": None,
        "top": 2,
        "top_left": None,
        "top_right": 1,
        "bottom_left": None,
        "bottom_right": None,
        "position_x": 0,
        "position_y": 1,
    }
]
