[workspace]

[profile.dev]
panic = "abort"

[profile.release]
lto = true
opt-level = "z"
panic = "abort"
codegen-units = 1
strip = true

[package]
name = "{{project-name}}"
version = "0.1.0"
authors = ["{{authors}}"]
edition = "2021"
include = ["src/**/*", "function.json", "*.star"]

[lib]
name = "{{crate_name}}"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
log = "0.4"
edgeless_function = { git = "https://github.com/edgeless-project/nextless.git", branch = "development", package = "edgeless_function" }
{% if generate_http_handler -%}
edgeless_function_types = { git = "https://github.com/edgeless-project/nextless.git", branch = "development", package = "edgeless_function_types", features = ["http"] }
serde = {version="1", features=["derive"] }
serde_json = "1"
{% else %}
edgeless_function_types = { git = "https://github.com/edgeless-project/nextless.git", branch = "development", package = "edgeless_function_types" }
{%- endif %}
{% if generate_matrix_output -%}
embedded-graphics = { version = "0.8" }
{%- endif %}

[features]
{%- assign inputs = cast_inputs | split: "," -%}
{%- assign outputs = cast_outputs | split: "," -%}

{%- for output in outputs %}
output_{{output}} = []
{%- endfor %}
{% if generate_matrix_output -%}
output_drawable = []
{% endif -%}

{%- for input in inputs %}
input_{{input}} = []
{%- endfor %}
{% if generate_http_handler -%}
input_http_request = []
{% endif -%}
