# SPDX-FileCopyrightText: © 2025 Technical University of Munich, Chair of Connected Mobility
# SPDX-License-Identifier: MIT
[workspace]

[profile.dev]
panic = "abort"

[profile.release]
lto = true
opt-level = "z"
panic = "abort"
codegen-units = 1
strip = true

[package]
name = "mock_producer"
version = "0.1.0"
authors = ["Raphael Hetzel <hetzel@in.tum.de>"]
edition = "2021"
include = ["src/**/*", "function.json", "*.star"]

[lib]
name = "mock_producer"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
edgeless_function = { git = "https://github.com/edgeless-project/nextless.git", branch = "development", package = "edgeless_function" }
edgeless_function_core = { git = "https://github.com/edgeless-project/nextless.git", branch = "development", package = "edgeless_function_core" }
edgeless_actor_abi = { git = "https://github.com/edgeless-project/nextless.git", branch = "development", package = "edgeless_actor_abi" }
log = "0.4"

[features]

output_output1 = []
output_output2 = []
output_output3 = []
output_output4 = []
output_output5 = []
output_output6 = []
output_output7 = []
output_output8 = []
output_output9 = []
output_output10 = []
