name: Edgeless Commit Checks
on:
  push:
jobs:
  check:
    runs-on:
      - ubuntu-latest
    container:
      image: ghcr.io/edgeless-project/ci-image:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}
    steps:
      - uses: actions/checkout@v4
      - name: Linter
        run: cargo fmt --check
      - name: Clippy
        run: cargo clippy --no-deps
      - name: Tests
        run: cargo test
  build:
    runs-on:
      - ubuntu-latest
    container:
      image: ghcr.io/edgeless-project/ci-image:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}
    steps:
      - uses: actions/checkout@v4
      - name: Build x64 Release
        run: cargo build --release
